import {
  Activity,
  AlertCircle,
  Archive,
  ArrowLeft,
  ArrowRight,
  ArrowUpRight,
  AtSign,
  BarChart3,
  Blocks,
  Boxes,
  BrainCircuit,
  Briefcase,
  Building2,
  Calendar,
  CalendarClock,
  Check,
  CheckCircle2,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronsUpDown,
  CircleDot,
  ClipboardCheck,
  Clock,
  CloudCog,
  Code2,
  Compass,
  Cpu,
  Database,
  ExternalLink,
  Eye,
  EyeOff,
  Factory,
  FileText,
  Filter,
  FolderKanban,
  Gauge,
  GitBranch,
  Globe,
  GraduationCap,
  HandHeart,
  Hash,
  HeartPulse,
  Home,
  Inbox,
  Info,
  Layers,
  LayoutDashboard,
  LifeBuoy,
  LineChart,
  Link2,
  Loader2,
  Lock,
  LogOut,
  Mail,
  Map,
  MapPin,
  Menu,
  MessageSquare,
  MessagesSquare,
  MonitorSmartphone,
  Network,
  Palette,
  Pencil,
  PenTool,
  Phone,
  Plus,
  Puzzle,
  Quote,
  RefreshCw,
  Rocket,
  Save,
  Search,
  Send,
  Server,
  ShieldCheck,
  ShoppingBag,
  Smartphone,
  Sparkles,
  Sprout,
  Star,
  Store,
  Tag,
  Target,
  Terminal,
  Timer,
  TrendingUp,
  Trash2,
  User,
  UserRoundCheck,
  Users,
  Wallet,
  Workflow,
  X,
  Zap,
  type LucideIcon,
} from "lucide-react";

/**
 * Explicit icon registry.
 *
 * Content modules reference icons by name. Resolving those names through a
 * static map (rather than `import * as lucide`) keeps tree-shaking effective,
 * so only the icons listed here reach the bundle.
 */
export const iconRegistry = {
  Activity,
  AlertCircle,
  Archive,
  ArrowLeft,
  ArrowRight,
  ArrowUpRight,
  AtSign,
  BarChart3,
  Blocks,
  Boxes,
  BrainCircuit,
  Briefcase,
  Building2,
  Calendar,
  CalendarClock,
  Check,
  CheckCircle2,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronsUpDown,
  CircleDot,
  ClipboardCheck,
  Clock,
  CloudCog,
  Code2,
  Compass,
  Cpu,
  Database,
  ExternalLink,
  Eye,
  EyeOff,
  Factory,
  FileText,
  Filter,
  FolderKanban,
  Gauge,
  GitBranch,
  Globe,
  GraduationCap,
  HandHeart,
  Hash,
  HeartPulse,
  Home,
  Inbox,
  Info,
  Layers,
  LayoutDashboard,
  LifeBuoy,
  LineChart,
  Link2,
  Loader2,
  Lock,
  LogOut,
  Mail,
  Map,
  MapPin,
  Menu,
  MessageSquare,
  MessagesSquare,
  MonitorSmartphone,
  Network,
  Palette,
  PenTool,
  Pencil,
  Phone,
  Plus,
  Puzzle,
  Quote,
  RefreshCw,
  Rocket,
  Save,
  Search,
  Send,
  Server,
  ShieldCheck,
  ShoppingBag,
  Smartphone,
  Sparkles,
  Sprout,
  Star,
  Store,
  Tag,
  Target,
  Terminal,
  Timer,
  Trash2,
  TrendingUp,
  User,
  UserRoundCheck,
  Users,
  Wallet,
  Workflow,
  X,
  Zap,
} satisfies Record<string, LucideIcon>;

export type IconName = keyof typeof iconRegistry;

interface IconProps extends React.SVGProps<SVGSVGElement> {
  name: string;
  size?: number;
}

/**
 * Renders a registry icon by name. Unknown names fall back to a neutral glyph
 * so a content typo degrades gracefully instead of crashing the page.
 */
export function Icon({ name, size = 20, ...props }: IconProps) {
  const Resolved = (iconRegistry as Record<string, LucideIcon>)[name] ?? CircleDot;
  return <Resolved size={size} strokeWidth={1.6} aria-hidden="true" {...props} />;
}
